# Generated by Django 6.0.4 on 2026-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('hackathon', 'Hackathon'), ('ideathon', 'Ideathon'), ('workshop', 'Workshop'), ('contest', 'Contest')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rewards', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_gained', models.JSONField(blank=True, default=list)),
                ('roi_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('performance_score', models.IntegerField(default=0)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
